# Generated by Django 4.2.6 on 2023-11-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewfor',
            options={'verbose_name': 'ReviewFor', 'verbose_name_plural': 'ReviewFor'},
        ),
        migrations.CreateModel(
            name='Zero_to_houndred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(to='main.product')),
            ],
            options={
                'verbose_name': 'Zero_to_houndred',
                'verbose_name_plural': 'Zero_to_houndred',
            },
        ),
    ]
