# Generated by Django 4.2.6 on 2023-11-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_reviewfor_options_zero_to_houndred'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Zero_to_houndred',
        ),
    ]
