# Generated by Django 4.1.4 on 2023-11-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurShop',
        ),
    ]
