# Generated by Django 4.1.4 on 2023-11-24 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereview',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prodreview', to='main.product'),
        ),
    ]
